---
title: "pcoa_alpha_plot"
output: html_document
date: "2023-10-23"
---

```{r, echo=FALSE, warning=F, message=FALSE}
#library(CPOP)
library(phyloseq)
library(stringr)
library(plyr); library(dplyr)
library(ggplot2); library(magrittr); library(ggfortify) ;require(reshape2)
suppressWarnings({suppressMessages({library(PD16Sdata)
                  library(vegan)
                  library(kableExtra)
                  library(knitr)
                  library(RColorBrewer)
                  library(glmnet)
                  library(ggplot2)
                  library(caTools)
                  library(e1071)
                  library(caret)
                  library(ggplot2)
                  library(readxl)
                  library(plotly)
                  library(MASS) ; library(plsdof) ; library(caret) ; library(boot); library(robustbase) ; library(randomForest)
      }
    )
  }
)
options(scipen = 1, digits=2)
```


```{r}
#library(microbiome)
remove_pca_outliers <- function(ps, out.pcoa, threshold_quantile = 0.9) {
  
  euclidean_distance <- function(x, y, centroid) {
    sqrt((x - centroid[1])^2 + (y - centroid[2])^2)
  }
  
  df <- data.frame(SampleID = sample_names(ps), 
                   PC1 = out.pcoa$vectors[, 1],
                   PC2 = out.pcoa$vectors[, 2])
  
  centroid <- c(mean(df$PC1, na.rm = TRUE), mean(df$PC2, na.rm = TRUE))
  
  distances <- apply(df[, 2:3], 1, function(row) euclidean_distance(row[1], row[2], centroid))
  
  threshold <- quantile(distances, threshold_quantile)
  
  outliers <- which(distances > threshold)
  
  # Extracting SampleIDs of the outliers
  samples_to_remove <- df$SampleID[outliers]
  samples_to_keep <- df$SampleID[-outliers]
  # Removing outliers from the phyloseq object
  ps_cleaned <- prune_samples(sample_names(ps) %in% samples_to_keep, ps)
  
  return(ps_cleaned)
}

beta_plot2 <- function(ps, title, remove_outliers = FALSE){
  
  ps <- subset_samples(ps, !is.na(PD))
  
  ps <- prune_taxa(taxa_sums(ps) > 0, ps)
  
  ps <- prune_samples(sample_sums(ps) > 50, ps)

  
  psra <- transform_sample_counts(ps, function(x){x / sum(x)})
  
  #psra@otu_table@.Data <- compositions::clr(psra@otu_table@.Data)
  
  out.pcoa <- ordinate(psra,  method = "MDS", distance = "jsd")
  if (remove_outliers){
    psra <- remove_pca_outliers(psra,out.pcoa)
    out.pcoa <- ordinate(psra,  method = "MDS", distance = "jsd")
    
  }
  evals <- out.pcoa$values[,1]
  df = cbind(out.pcoa$vectors[,1:3],psra@sam_data)  %>% arrange(PD,.by_group = TRUE)
  
  
  var_explained = out.pcoa$values$Relative_eig[1:3]

  p12 <- ggplot(df) + geom_point(aes(x = Axis.1, y = Axis.2, color = PD), size = 2) + labs(x = paste0("PC1: ", 100*round(var_explained[1],digits = 4), "%"), y = paste0("PC2: ", 100*round(var_explained[2],digits = 4), "%")) +  theme_classic()  + stat_ellipse(aes(x = Axis.1, y = Axis.2, group = PD, color = PD, lty = PD), level = 0.9) + scale_color_manual(values = brewer.pal(3, "Set2")) + ggtitle(title)
  return (p12)
}
```

```{r}
alpha_plot3 <- function(ps, ylab, title){
  ps <- subset_samples(ps, !is.na(PD))
  ps <- subset_taxa(ps, !is.na(Phylum) & !Phylum %in% c("", "uncharacterized"))
  S_shannon <- vegan::diversity(ps@otu_table, index = "shannon", MARGIN = 1)
  D_alpha <- ps@sam_data
  D_alpha <- as.data.frame(as.matrix(D_alpha))
  D_shannon <- D_alpha
  D_shannon$shannon <- S_shannon
  
  p <- ggplot(data = D_shannon) + geom_boxplot(aes(x = PD,y = shannon,fill = PD), width = 0.2) + 
    labs(x = "",y = ylab, title = title) + ylim(1,5.5) + theme_bw() + 
    theme(axis.text.x = element_text(color = "black"),
    plot.title = element_text(size = 10, face = "bold"),
    strip.background = element_rect(fill = "white"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_line(color = "white", size = 0.4),
    panel.grid.minor.x = element_blank(),
    legend.text.align = 0,
    legend.key.height = unit(4, "mm"),
    legend.key.width = unit(4, "mm"),
    legend.text = element_text(size = 9),
    legend.margin = ggplot2::margin(r = 7, unit = "mm")) + 
    scale_fill_manual(values = c("#BF812D", "aquamarine4", "#9970AB")) + guides(fill = F) 
    
  return(p)
}
alpha_plot2 <- function(ps, ylab, title){
  ps <- subset_samples(ps, !is.na(PD))
  ps <- subset_taxa(ps, !is.na(Phylum) & !Phylum %in% c("", "uncharacterized"))
  S_shannon <- vegan::diversity(ps@otu_table, index = "shannon", MARGIN = 1)
  D_alpha <- ps@sam_data
  D_alpha <- as.data.frame(as.matrix(D_alpha))
  D_shannon <- D_alpha
  D_shannon$shannon <- S_shannon
  
  p <- ggplot(data = D_shannon) + geom_boxplot(aes(x = PD,y = shannon,fill = PD), width = 0.2) + 
    labs(x = "",y = ylab,title = title)+ ylim(1,5.5)  + theme_bw() + 
    theme(
    strip.background = element_rect(fill = "white"),
    plot.title = element_text(size = 10, face = "bold"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_line(color = "white", size = 0.4),
    panel.grid.minor.x = element_blank(),
    legend.text.align = 0,
    legend.key.height = unit(4, "mm"),
    legend.key.width = unit(4, "mm"),
    legend.text = element_text(size = 9),
    legend.margin = ggplot2::margin(r = 7, unit = "mm"),
    axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank()) + 
    scale_fill_manual(values = c("#BF812D", "aquamarine4", "#9970AB")) + guides(fill = F) 
  return(p)
}
```


```{r, warning=F, message=F, cache=TRUE}
ps1 <- ps_list$Lubomski
ps1 <- subset_samples(ps1, t==0)
ps2 <- ps_list$Wallen1
ps3 <- ps_list$Wallen2
ps4 <- ps_list$`Hill-Burns`
ps5 <- ps_list$Aho
ps6 <- ps_list$Weils
ps7 <- ps_list$Jin
ps8 <- ps_list$Scheperjans
```




```{r, cache=TRUE}
b1 <- beta_plot2(ps1, "Lubomski") 
b2 <- beta_plot2(ps2, "Wallen1", remove_outliers = T) ;b3 <- beta_plot2(ps3, "Wallen2");b4 <- beta_plot2(ps4, "Hills-Burns")
b5 <- beta_plot2(ps5, "Aho");b6 <- beta_plot2(ps8, "Schep")

```






```{r}
library(gridExtra)
library(ggpubr)
ggarrange(b1,b2,b3,b4,b5,b6, ncol=3, nrow=2,common.legend = TRUE, legend="right")
dev.copy(png,filename="beta.png", width = 2500, height = 1200,res=170);
dev.off (); 
```

```{r}
alpha_list <- list(ps1,ps2,ps3,ps4,ps5,ps6,ps7,ps8)
plot_list <- list(alpha_plot2(ps1, "Shannon Diversity", "Lubomski"), alpha_plot2(ps2, "", "Wallen1"),alpha_plot2(ps3, "", "Wallen2"),
                  alpha_plot3(ps5, "Shannon Diversity", "Aho"),alpha_plot3(ps8, "", "Scheperjans"),alpha_plot3(ps4, "", "Hills-Burns"))
```
```{r}
library(gridExtra)
grid.arrange(plot_list[[1]],plot_list[[2]],plot_list[[3]],plot_list[[4]],
             plot_list[[5]],plot_list[[6]], ncol=3)
# dev.copy(jpeg,filename="Shannon2.jpg", width = 1600, height = 1200,res=300);
# dev.off ();
```



